title: PostGIS Rocks!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://postgisday.rocks" # the base hostname & protocol for your site, e.g. http://example.com

# Custom variables
description: >-
  Every year on the Thursday of the third week of November, 
  we celebrate our favourite spatial database

show_downloads: false

author:
  name: Jorge Sanz
  email: xurxosanz@gmail.com

repository: geoinquietos-org/postgisday
google_analytics: UA-56908901-1

plugins:
  - jekyll-gist
  - jekyll-seo-tag

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


# Build settings
highlighter: rouge
markdown: kramdown
theme: jekyll-theme-midnight
lsi: false

# SEO tag
twitter:
  username: xurxosanz

social:
  name: Jorge Sanz
  links:
    - https://twitter.com/xurxosanz
    - https://www.linkedin.com/in/jsanz
    - https://github.com/jsanz
    - https://keybase.io/jsanz

include:
  - "_pages"

exclude:
  - LICENSE
  - CNAME
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Makefile
  - .vscode

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author: Trolpical
      author_twitter: trolpical
