title:               PostGIS Rocks!
baseurl:             "" # the subpath of your site, e.g. /blog
url:                 "http://postgisday.geoinquietos.org" # the base hostname & protocol for your site, e.g. http://example.com

# Custom variables
description: >-
                     It's the third Thursday of November, and as every year, 
                     also a day to celebrate our favourite spatial database

author:
  name:              Jorge Sanz
  email:             xurxosanz@gmail.com

google_analytics:    UA-56908901-1

plugins:
  - jekyll-gist
  - jekyll-seo-tag


# Build settings
highlighter:        rouge
markdown:           kramdown
theme:              jekyll-theme-hacker
lsi:                false

# SEO tag
twitter:
  username: xurxosanz

social:
  name: Jorge Sanz
  links:
    - https://twitter.com/xurxosanz
    - https://www.linkedin.com/in/jsanz
    - https://github.com/jsanz
    - https://keybase.io/jsanz

include:
                    - "_pages"

exclude: 
                    - LICENSE
                    - CNAME
                    - README.md
                    - .gitignore
                    - Gemfile
                    - Gemfile.lock


defaults:
  - scope:
      path: ""
      type: posts
    values:
      author: Trolpical
      author_twitter: trolpical