version: '3'

services:
  jekyll:
    build:
      context: .
    command: jekyll serve --watch --port 8080 -H 0.0.0.0 --livereload --livereload-port 35729
    volumes:
      - .:/srv/jekyll
      - jekyll:/usr/local/bundle
    ports:
      - '8080:8080'
      - '35729:35729'
    environment: 
      RUBYOPT: '-W0'
      JEKYLL_ENV: production 
volumes:
    jekyll:
